# General

For more informations, see the documentation *LLM and GenAI*.

# Import & Configs

In [7]:
import json
import pandas as pd

In [8]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [9]:
%load_ext autoreload
%autoreload 2

from src.retrieval.retriever import MedicalRetriever
from src.pipeline.medical_assistant import ask_medical_assistant

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Questions Set

In [10]:
with open(
    "../data/evaluations/gold_questions.json"
) as f:

    questions = json.load(f)

questions

[{'question': 'What is glioblastoma?'},
 {'question': 'How is glioblastoma prognosis evaluated?'},
 {'question': 'What MRI techniques are used for glioblastoma?'},
 {'question': 'What is peritumoral edema?'},
 {'question': 'What is pseudoprogression?'},
 {'question': 'How is tumor progression detected?'},
 {'question': 'What biomarkers are associated with glioblastoma?'},
 {'question': 'What are the limitations of MRI in glioma diagnosis?'},
 {'question': 'How is overall survival measured?'},
 {'question': 'What treatments are commonly used for glioblastoma?'}]

# Retrieval Evaluation

In [11]:
retriever = MedicalRetriever()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [12]:
results_retriever = []

for item in questions:
    
    question = item["question"]
    print(f'{question:-^80}')
    #output = retriever.retrieve(question)
    output = retriever.retrieve_diverse_articles(question)
    results_retriever.append(output)
    print('\n')
    for key, val in output.items():
        #print(f'--- {key}:')
        if key == 'documents':
            for i, doc in enumerate(val[0]):
                print(f'[{output['ids'][0][i]}]\n{doc}\n')
        else:
            #print(f'{val}')
            pass
        #print('\n')
    print("\n\n")

-----------------------------What is glioblastoma?------------------------------
Original query: What is glioblastoma?
Processed query: glioblastoma


[39513861_0]
The Three Pillars of Glioblastoma: A Systematic Review and Novel Analysis of Multi-Omics and Clinical Data. Glioblastoma is the most fatal and common malignant brain tumor, excluding metastasis and with a median survival of approximately one year. While solid tumors benefit from newly approved drugs, immunotherapy, and prevention, none of these scenarios are opening for glioblastoma.

[40542948_0]
Unlocking glioblastoma: breakthroughs in molecular mechanisms and next-generation therapies. Glioblastoma (GB) remains the most aggressive primary brain tumor in adults, characterized by rapid progression, recurrence, and resistance to conventional therapies. Despite advancements in surgical resection, radiation, and chemotherapy, long-term survival rates remain low.

[41777607_0]
Neurosurgical and neuro-oncological outcomes of confirmatory brain biopsies in patients with glioblastoma: a real-life monocentric experience. INTRODUCTION: Glioblastoma (GB) is an uncurable tumor with poor prognosis despite resection plus adjuvant cares. When unresectable, even in case of a clear radiological imaging, guidelines require a formal histological diagnosis to confirm the diagnosis of GB.




--------------------How is glioblastoma prognosis evaluated?--------------------
Original query: How is glioblastoma prognosis evaluated?
Processed query: glioblastoma prognosis evaluated


[41091233_5]
Conditional 5-year survival after surviving one year remained low for glioblastoma (11.0%) but exceeded 85% for most lower-grade tumors. CONCLUSION: Our findings underscore the prognostic relevance of tumor grade and histology, supporting the need for tailored clinical strategies, molecular diagnostics, and the development of innovative therapies for informed healthcare planning and resource allocation.

[39731064_6]
This systematic review summarizes the current state-of-the-art methods for predicting glioblastoma survival using different types of input data, such as clinical features, molecular markers, imaging features, radiomics features, omics data or a combination of them. Following PRISMA guidelines, we searched databases from 2015 to 2024, reviewing 107 articles meeting our criteria. We analyzed the data sources, methods, performance metrics and outcomes of the studies.

[36012105_0]
Molecular Biomarkers in Glioblastoma: A Systematic Review and Meta-Analysis. Background: Glioblastoma (GBM) is a highly aggressive cancer with poor prognosis that needs better treatment modalities. Moreover, there is a lack of reliable biomarkers to predict the response and outcome of current or newly designed therapies. While several molecular markers have been proposed as potential biomarkers for GBM, their uptake into clinical settings is slow and impeded by marker heterogeneity.




-----------------What MRI techniques are used for glioblastoma?-----------------
Original query: What MRI techniques are used for glioblastoma?
Processed query: mri techniques used for glioblastoma


[41749898_0]
Exploring the Role of Advanced MRI in Understanding Glioblastoma Biology: A Scoping Review. BACKGROUND: Among adult primary brain tumours, glioblastoma (GBM) carries the worst prognosis. Magnetic resonance imaging (MRI) serves to diagnose and guide treatment, despite recognised constraints.

[42162948_0]
Impact on survival of glioblastoma patient's in relation to the imaging of the peri-surgical area: a multi-parametric diffusion MRI, perfusion MRI and [11C]MET PET study. OBJECTIVES: Glioblastoma (GBM) is an aggressive brain tumour with poor prognosis; recurrence near the surgical cavity is common despite multimodal-treatment. Conventional MRI lacks accuracy for early detection of recurrence and cannot reliably differentiate progression from pseudoprogression.

[42134380_1]
We aimed to show the safety of a small-margin, MRI-guided adaptive radiotherapy approach for glioblastoma. METHODS: This single-arm, phase 2 trial was done at Sunnybrook Health Sciences Centre, Toronto, ON, Canada, and included patients with pathologically confirmed glioblastoma and planned for concurrent daily chemoradiotherapy up to 60 Gy in 30 daily fractions over 6 weeks (long course) or 40 Gy in 15 daily fractions over 3 weeks (short course).




---------------------------What is peritumoral edema?---------------------------
Original query: What is peritumoral edema?
Processed query: peritumoral edema


[41740788_1]
(2) For 2 patients, we took the following measures to ensure a smooth operation (Video). First, preoperative MRI showed that there was obvious peritumoral brain edema in both cases. Peritumoral edema can arise from venous compression or from vascular permeability and inflammation. We administered steroids to both patients preoperatively to reduce the edema caused by vascular permeability, so as to obtain more operative space during the operation.

[42217213_1]
Notwithstanding its benign classification, SM is frequently associated with excessive peritumoral brain edema (PTBE), resulting in considerable morbidity. This study examines the epidemiology, clinical presentation, imaging characteristics, histological features, immunohistochemical profile, and genetic landscape of SM, along with management methods and results.

[38254159_4]
All tumors showed significant enhancement, with homogeneous enhancement being more common, and most patients showed peritumoral edema. Postoperative pathological EMA, LCA, and vimentin positivity were helpful for the final diagnosis of the patient. Log-rank tests showed a correlation between complete resection and better prognosis and recurrence.




---------------------------What is pseudoprogression?---------------------------
Original query: What is pseudoprogression?
Processed query: pseudoprogression


[38992848_0]
Perioperative imaging predictors of tumor progression and pseudoprogression: A systematic review. In high-grade gliomas, pseudoprogression after radiation treatment might dramatically impact patient's management. We searched for perioperative imaging predictors of pseudoprogression in high-grade gliomas according to PRISMA guidelines, using MEDLINE/Pubmed and Embase (until January 2024).

[40768078_0]
Artificial intelligence algorithms for differentiating pseudoprogression from true progression in high-grade gliomas: A systematic review and meta-analysis. Differentiating pseudoprogression (PsP) from true progression (TP) in high-grade glioma (HGG) patients is still challenging and critical for effective treatment management. This meta-analysis evaluates the diagnostic accuracy of artificial intelligence (AI) algorithms in making this distinction.

[40360047_6]
Additional subclassification was performed based on MRI sequences evaluated or by the nature of the alterations, with pseudoprogression generally reserved for glioma patients. While many papers exist on MRI alterations in the brain after RT, this review highlights significant inconsistencies in the terminology and definitions, limiting the comparability of findings across studies.




-----------------------How is tumor progression detected?-----------------------
Original query: How is tumor progression detected?
Processed query: tumor progression detected


[41927498_5]
Several tumor relapse patterns were associated with patients' progression-free and overall survival (e.g., unifocal local and multicentric recurrences; p < 0.05), even when other known prognostic factors were taken into account. TTFields were associated with prolonged progression-free survival (mPFS 7.2 months vs. 4.8 months, p = 0.03).

[42079831_5]
Among patients with residual findings, 76 (64.4%) exhibited stable tumors after a mean of follow-up of 39 months, while 42 (35.6%) showed progression, which correlated significantly with larger preoperative tumor volumes (median: 11.6 cm(3) vs. 5.81 cm(3), p < 0.001). ROC analysis identified 7.12 cm(3) as the optimal cutoff for distinguishing stable from progressive residual tumor volumes (AUC = 0.748).

[41398618_4]
RESULTS: Residual tumour was present in 107 patients (61.5%) and progressed in 29 (27.1%) after a median of 47 months. Among 67 patients with complete resection, recurrence occurred in 15 (22.4%) after a median of 67 months. Most residual growths (62.1%) occurred within 5 years, while two-thirds of recurrences appeared after 5 years.




---------------What biomarkers are associated with glioblastoma?----------------
Original query: What biomarkers are associated with glioblastoma?
Processed query: biomarkers associated with glioblastoma


[36012105_0]
Molecular Biomarkers in Glioblastoma: A Systematic Review and Meta-Analysis. Background: Glioblastoma (GBM) is a highly aggressive cancer with poor prognosis that needs better treatment modalities. Moreover, there is a lack of reliable biomarkers to predict the response and outcome of current or newly designed therapies. While several molecular markers have been proposed as potential biomarkers for GBM, their uptake into clinical settings is slow and impeded by marker heterogeneity.

[40136660_4]
Additionally, biomarkers in glioblastoma showed prognostic value, while those in hepatocellular and pancreatobiliary cancers exhibited potential for early detection. However, gastric and prostate cancer biomarkers showed limited reliability, and breast cancer biomarkers require further validation.

[42274584_3]
This review highlights the role of these three key cancer-related pathways in glioblastoma and their mechanistic link. Better understanding these links may result in improved treatment targets or disease progression biomarkers.




--------------What are the limitations of MRI in glioma diagnosis?--------------
Original query: What are the limitations of MRI in glioma diagnosis?
Processed query: limitations of mri in glioma diagnosis


[42135047_0]
[Clinical practice guideline for integrated PET/MRI in brain gliomas(2026 edition)].

[41749898_0]
Exploring the Role of Advanced MRI in Understanding Glioblastoma Biology: A Scoping Review. BACKGROUND: Among adult primary brain tumours, glioblastoma (GBM) carries the worst prognosis. Magnetic resonance imaging (MRI) serves to diagnose and guide treatment, despite recognised constraints.

[42095926_1]
METHODS: Clinical 3-Tesla brain MRI images from 644 patients with pathologically confirmed adult-diffuse glioma before treatment was retrospectively evaluated: 527 IDH-wildtype glioblastoma, 71 astrocytoma, and 46 oligodendroglioma. Pre- and post-contrast T1-weighted, T2-weighted and FLAIR sequences were part of the MRI protocol. Contrast-enhancing tumors and non-enhancing lesions (NEL) were automatically segmented using HD-GLIO.




-----------------------How is overall survival measured?------------------------
Original query: How is overall survival measured?
Processed query: overall survival measured


[42131752_2]
Associations between quality indicators, site characteristics and median overall survival (mOS) were examined. RESULTS: A total of 364 patient files were evaluated at 19 sites.

[41689093_8]
Survival outcomes will be analyzed using Kaplan-Meier methods with log-rank test. Neurocognitive and quality-of-life data will be evaluated using linear mixed-effects and non-parametric tests. A total of 156 patients will be enrolled, accounting for 20% attrition, to detect a 25% absolute improvement in 5-year functional survival favoring PBT (65% vs 40%, HR 0.47, alpha=0.05, power=80%). An interim analysis has been planned using the O'Brien-Fleming rule after 50% of the events (n=28).

[42218248_2]
Survival was analyzed using the Kaplan-Meier method, log-rank test, and Cox regression. RESULTS: In the single-center cohort, no significant differences were observed among the three groups in objective response rate (ORR; P = 0.693), disease control rate (DCR; P = 1.000), median progression-free survival (PFS; 6, 7, and 8 months, respectively; P = 0.621), or median OS (11, 13, and 13 months, respectively; P = 0.534).




--------------What treatments are commonly used for glioblastoma?---------------
Original query: What treatments are commonly used for glioblastoma?
Processed query: treatments commonly used for glioblastoma


[39618405_0]
Targeted agents in patients with progressive glioblastoma-A systematic meta-analysis of randomized clinical trials. BACKGROUND: Glioblastoma (GB) is the most common malignant primary brain tumor in adults and is associated with a poor prognosis. Current treatment guidelines outline the standard of care for patients with newly diagnosed GB; however, there is currently no well-established consensus for the treatment of progressive GB.

[24740195_0]
The role of targeted therapies in the management of progressive glioblastoma : a systematic review and evidence-based clinical practice guideline. QUESTION: What is the influence of targeted medical therapies on disease control and survival in the adult patient with progressive glioblastoma?

[34559423_2]
OBJECTIVES: To evaluate the effectiveness of further treatment/s for first and subsequent progression or recurrence of glioblastoma (GBM) among people who have received the standard of care (Stupp protocol) for primary treatment of the disease; and to prepare a brief economic commentary on the available evidence. SEARCH METHODS: We searched MEDLINE and Embase electronic databases from 2005 to December 2019 and the Cochrane Central Register of Controlled Trials (CENTRAL, in the Cochrane Library; Issue 12, 2019).

### V1

| Question  | Retrieval | Comments |
|-----|:-----:|-----|
| Q1 | 4 |  |
| Q2 | 3 |  |
| Q3 | 2 |  |
| Q4 | 3 | Confusion btw glioma & glioblastoma |
| Q5 | 1 | Not Relevant | 
| Q6 | 2 | Relevance ? | 
| Q7 | 3 |  |
| Q8 | 2 | Only doc 1 is relevant |
| Q9 | 2 | Doc 1 : not relevant |
| Q10 | 1 | Confusion btw glioma & glioblastoma |

With:
- 1 = bad
- 5 = excellent

**Definitions:**
- **Retrieval:** Have the correct documents been found?

Identified Limitations:
- Chunks that are too specialized.
- Chunks at the wrong level
- Diversification issues

### V2

| Question  | Retrieval | Comments |
|-----|:-----:|-----|
| Q1 | 4 | 1 doc too large, others good |
| Q2 | 3 | Correct, but not ideal |
| Q3 | 4 |  |
| Q4 | 4 |  |
| Q5 | 3 | Doc 2 : weak | 
| Q6 | 2 | progression more than detection | 
| Q7 | 4 |  |
| Q8 | 2 | Only doc 1 is relevant |
| Q9 | 1 | Not relevant |
| Q10 | 2 | Standard treatments not found |

With:
- 1 = bad
- 5 = excellent

**Definitions:**
- **Retrieval:** Have the correct documents been found?

## V3

In [ ]:
[5,4,5,4,5,2,5,3,2,3]
[
    "Two excellent definitional reviews in the top spots.",
    "Relevant documents on survival, biomarkers, and prognostic prediction. Not perfect, but sufficient.",
    "Excellent MRI documents, including a dedicated review.",
    "The literature clearly defines peritumoral edema even outside the context of glioblastoma.",
    "The best available evidence comes to light immediately (SR + meta-analysis).",
    "The documents focus primarily on tumor progression, not on its detection.",
    "Excellent summary, with a systematic review focused on biomarkers.",
    "A relevant review, but the other documents are not very relevant to the question.",
    "Documents that mention survival measures but do not provide a direct explanation from the OS.",
    "Treatments are available, but mainly in the context of recurrence or disease progression. They aren't really the standard treatments for GBM."
]

| Question  | Retrieval | Comments |
|-----|:-----:|-----|
| Q1 | 5 | Two excellent definitional reviews in the top spots. |
| Q2 | 4 | Relevant documents on survival, biomarkers, and prognostic prediction. Not perfect, but sufficient. |
| Q3 | 5 | Excellent MRI documents, including a dedicated review. |
| Q4 | 4 | The literature clearly defines peritumoral edema even outside the context of glioblastoma. |
| Q5 | 5 | The best available evidence comes to light immediately (SR + meta-analysis). | 
| Q6 | 2 | The documents focus primarily on tumor progression, not on its detection. | 
| Q7 | 5 | Excellent summary, with a systematic review focused on biomarkers. |
| Q8 | 3 | A relevant review, but the other documents are not very relevant to the question. |
| Q9 | 2 | Documents that mention survival measures but do not provide a direct explanation from the OS. |
| Q10 | 3 | Treatments are available, but mainly in the context of recurrence or disease progression. They aren't really the standard treatments for GBM. |

With:
- 1 = bad
- 5 = excellent

**Definitions:**
- **Retrieval:** Have the correct documents been found?

# Answer Evaluation

In [13]:
results_answer = []

for item in questions:
    
    question = item["question"]
    print(f'{question:-^80}')

    output = ask_medical_assistant(
        question,
        retriever,
        #debug=True
    )

    results_answer.append(output)
    print("\n\n")

-----------------------------What is glioblastoma?------------------------------
Original query: What is glioblastoma?
Processed query: glioblastoma
Loaded 3307 articles.
Glioblastoma is the most fatal and common malignant brain tumor, excluding metastasis and with a median survival of approximately one year. It is characterized by rapid progression, recurrence, and resistance to conventional therapies. Despite advancements in surgical resection, radiation, and chemotherapy, long-term survival rates remain low.
Sources used:
[1] The Three Pillars of Glioblastoma: A Systematic Review and Novel Analysis of Multi-Omics and Clinical Data (2024) PMID:39513861
[2] Unlocking glioblastoma: breakthroughs in molecular mechanisms and next-generation therapies (2025) PMID:40542948
[3] Neurosurgical and neuro-oncological outcomes of confirmatory brain biopsies in patients with glioblastoma: a real-life monocentric experience (2026) PMID:41777607




--------------------How is glioblastoma prognosis evaluated?--------------------
Original query: How is glioblastoma prognosis evaluated?
Processed query: glioblastoma prognosis evaluated
Glioblastoma prognosis is evaluated using several factors, including tumor grade and histological subtype. The study notes that glioblastoma was the most frequent subtype (64.6%), followed by grade 2-3 meningiomas (18.2%) and astrocytomas (9.4%). Additionally, it provides information on relative survival rates for different tumors and grades, indicating that glioblastoma has the poorest outcome with a crude incidence of 8.0 per 100,000, while grade 2-3 ependymomas and oligodendrogliomas show favorable prognosis (87.7% and 82.0%, respectively).
Sources used:
[1] Incidence and survival of adult central nervous system tumors in the Veneto region: a population-based registry study (2016-2020) (2025) PMID:41091233
[2] Survival prediction of glioblastoma patients using machine learning and deep learning: a systematic review (2024) PMID:39731064
[3] Molecular Biomarkers in Glioblastoma: A Systematic Review and Meta-Analysis (2022) PMID:36012105




-----------------What MRI techniques are used for glioblastoma?-----------------
Original query: What MRI techniques are used for glioblastoma?
Processed query: mri techniques used for glioblastoma
Magnetic resonance spectroscopy (MRS), amide proton transfer-weighted imaging (APTw), diffusion-weighted imaging (DWI), perfusion-weighted imaging (PWI), and quantitative susceptibility mapping (QSM) are used for glioblastoma.
Sources used:
[1] Exploring the Role of Advanced MRI in Understanding Glioblastoma Biology: A Scoping Review (2026) PMID:41749898
[2] Impact on survival of glioblastoma patient's in relation to the imaging of the peri-surgical area: a multi-parametric diffusion MRI, perfusion MRI and [11C]MET PET study (2026) PMID:42162948
[3] MRI-guided adaptive radiotherapy for high grade glioma (UNITED): a single-centre, single-arm, non-inferiority, phase 2 trial (2026) PMID:42134380




---------------------------What is peritumoral edema?---------------------------
Original query: What is peritumoral edema?
Processed query: peritumoral edema
Peritumoral edema can arise from venous compression or from vascular permeability and inflammation.
Sources used:
[1] Resection of the Clinoidal Meningioma Encasing the Carotid Artery: A Complex and Delicate Surgical Procedure (2026) PMID:41740788
[2] From Imaging to Molecular Pathways: A Comprehensive Narrative Review of the Distinctive Landscape of Secretory Meningioma (2026) PMID:42217213
[3] Epidemiology, characteristics, and prognostic factors of lymphoplasmacyte-rich meningioma: a systematic literature review (2024) PMID:38254159




---------------------------What is pseudoprogression?---------------------------
Original query: What is pseudoprogression?
Processed query: pseudoprogression
Pseudoprogression refers to an apparent improvement or regression in tumor size that does not actually represent true disease progression, but rather represents a response to treatment. It can be particularly challenging to differentiate from true progression in high-grade gliomas due to its potential impact on patient management and outcomes.
Sources used:
[1] Perioperative imaging predictors of tumor progression and pseudoprogression: A systematic review (2024) PMID:38992848
[2] Artificial intelligence algorithms for differentiating pseudoprogression from true progression in high-grade gliomas: A systematic review and meta-analysis (2025) PMID:40768078
[3] Systematic review of MRI alterations in the brain following proton and photon radiation therapy: Towards a uniform European Particle Therapy Network (EPTN) definition (2025) PMID:40360047




-----------------------How is tumor progression detected?-----------------------
Original query: How is tumor progression detected?
Processed query: tumor progression detected
Tumor progression in non-functioning pituitary macroadenomas following transnasal transsphenoidal resection is detected through the analysis of postoperative MRI data. The study identifies several predictive factors for progression, including preoperative and postoperative tumor volumes, Hardy or Knosp classifications, and management strategies such as cortisol levels.
Sources used:
[1] Regrowth Patterns in Glioblastoma-Survival and Predictors (2026) PMID:41927498
[2] Predicting tumor progression in non-functioning pituitary macroadenomas following transnasal transsphenoidal resection: insights from a single-center retrospective cohort study (2026) PMID:42079831
[3] Rethinking the Long-Term Follow-Up Strategy for Non-Functioning Pituitary Neuroendocrine Tumours in a Real-World Setting (2026) PMID:41398618




---------------What biomarkers are associated with glioblastoma?----------------
Original query: What biomarkers are associated with glioblastoma?
Processed query: biomarkers associated with glioblastoma
MGMT promoter methylation is significantly associated with better overall survival (OS) in GBM patients, as indicated by a pooled hazard ratio of 1.66 (95% CI: 1.32-2.09), p < 0.0001, using random effect model.
Sources used:
[1] Molecular Biomarkers in Glioblastoma: A Systematic Review and Meta-Analysis (2022) PMID:36012105
[2] Salivary Extracellular Vesicles in Detection of Cancers Other than Head and Neck: A Systematic Review (2025) PMID:40136660
[3] The Signaling Networks of TIM-3, TGF-beta, and STING in Glioblastoma (2026) PMID:42274584




--------------What are the limitations of MRI in glioma diagnosis?--------------
Original query: What are the limitations of MRI in glioma diagnosis?
Processed query: limitations of mri in glioma diagnosis
MRI, or magnetic resonance imaging, has several limitations in diagnosing gliomas. These include:

1. **Contrast-Enhancing Tumors and Non-Enhancing Lesions (NELs):** MRI relies on contrast agents to enhance visibility of tumors, but not all gliomas are well-differentiated enough for this method to be effective.

2. **Signal Intensity Variability:** The signal intensity in different sequences can vary significantly between glioma types, making it difficult to differentiate between them using standard MRI techniques alone.

3. **Tumor Location and Size:** MRI is less sensitive to small or non-contrast-enhancing tumors, which are common in many gliomas. Additionally, the location of a tumor within the brain can affect
Sources used:
[1] [Clinical practice guideline for integrated PET/MRI in brain gliomas(2026 edition)] (2026) PMID:42135047
[2] Exploring the Role of Advanced MRI in Understanding Glioblastoma Biology: A Scoping Review (2026) PMID:41749898
[3] IDH status shapes glioma oncotopy: voxel-wise mapping of 644 adult diffuse gliomas (2026) PMID:42095926




-----------------------How is overall survival measured?------------------------
Original query: How is overall survival measured?
Processed query: overall survival measured
Overall survival (OS) was measured using the Kaplan-Meier method, log-rank test, and Cox regression in both studies.
Sources used:
[1] European neuro-oncology quality assessment (ENOQUA): A European organization for the research and treatment of cancer (EORTC) brain tumor group research project (2026) PMID:42131752
[2] Proton versus photon radiotherapy in adults with primary brain tumors evaluating functional survival: a phase 3 randomized controlled trial study protocol (PRIDE) (2026) PMID:41689093
[3] Efficacy of chemoradiotherapy in pediatric H3K27M-mutant diffuse intrinsic pontine glioma: a study based on single-center and SEER data (2026) PMID:42218248




--------------What treatments are commonly used for glioblastoma?---------------
Original query: What treatments are commonly used for glioblastoma?
Processed query: treatments commonly used for glioblastoma
The context does not provide specific information about the most common treatments used for glioblastoma. It mentions that there is no consensus regarding the best treatment/s to offer people upon disease progression or recurrence, and it provides evidence on various therapies including bevacizumab, regorafenib, lomustine (CCNU), temozolomide (TMZ) plus depatux-M (ABT414), and fotemustine. However, the context does not specify which of these treatments are commonly used in practice or as first-line treatment options.
Sources used:
[1] Targeted agents in patients with progressive glioblastoma-A systematic meta-analysis of randomized clinical trials (2024) PMID:39618405
[2] The role of targeted therapies in the management of progressive glioblastoma : a systematic review and evidence-based clinical practice guideline (2014) PMID:24740195
[3] Treatment options for progression or recurrence of glioblastoma: a network meta-analysis (2021) PMID:34559423

### V1

| Question  | Relevance | Faithfulness | Clarity |
|:-----|:-----:|:-----:|:-----:|
| Q1 | 5 | 5 | 5 |
| Q2 | 4 | 4 | 3 |
| Q3 | 2 | 4 | 4 |
| Q4 | 5 | 5 | 4 |
| Q5 |  4 | 4 | 4 |
| Q6 |  3 | 3 | 4 |
| Q7 |  2 | 4 | 4 |
| Q8 |  5 | 5 | 4 |
| Q9 |  1 | 4 | 3 |
| Q10 |  1 | 5 | 2 |

With:
- 1 = bad
- 5 = excellent



**Definitions:**
- **Relevance:** Does it answer the question?
- **Accuracy:** Is it accurate in the context?
- **Clarity:** Is it understandable?


Identified limitations:
- Duplicate documents
- Overly simplistic retrieval
- Insufficient model

### V2

| Question  | Relevance | Faithfulness | Clarity | Comments |
|:-----|:-----:|:-----:|:-----:|:-----|
| Q1 | 5 | 4 | 5 | “10–20% of all primary brain tumors” seems far-fetched. |
| Q2 | 3 | 5 | 4 | Answer too specific (hematology) |
| Q3 | 3 | 4 | 4 | DWI/IVIM/DSC are explicitly in the excerpts provided ? |
| Q4 | 5 | 5 | 5 |  |
| Q5 |  4 | 5 | 5 |  |
| Q6 |  3 | 5 | 4 | “how progression patterns are studied” rather than “how progression is detected.” |
| Q7 |  3 | 5 | 5 | response too restrictive regarding biomarkers |
| Q8 |  4 | 4 | 4 | Some limitations are well-founded, while others seem to be extrapolated. |
| Q9 |  1 | 5 | 3 | off-topic |
| Q10 |  1 | 5 | 1 | “I don't know” makes sense in the context but does not answer the user's question. |

With:
- 1 = bad
- 5 = excellent



**Definitions:**
- **Relevance:** Does it answer the question?
- **Accuracy:** Is it accurate in the context?
- **Clarity:** Is it understandable?

## V3

| Question  | Relevance | Faithfulness | Clarity | Comments |
|:-----|:-----:|:-----:|:-----:|:-----|
| Q1 | 5 | 5 | 5 | A short, accurate answer directly supported by the sources. |
| Q2 | 3 | 4 | 4 | Partially answers the question. The model focuses more on observed survival than on prognostic assessment. |
| Q3 | 5 | 5 | 5 | A direct and comprehensive answer. |
| Q4 | 5 | 5 | 5 | A clear and accurate definition. |
| Q5 |  5 | 5 | 5 | A very good definition of pseudoprogression. |
| Q6 |  2 | 4 | 3 | Off-topic response: factors influencing progression rather than detection methods. |
| Q7 |  3 | 5 | 4 | Correct, but too restrictive: only one biomarker is mentioned. |
| Q8 |  4 | 3 | 4 | A plausible answer, but several limitations seem to have been extrapolated from the context. |
| Q9 |  4 | 5 | 4 | Correctly answer the question using the OS's statistical measurement methods. |
| Q10 |  1 | 5 | 4 | The model implicitly acknowledges the lack of context. The response is accurate but does not answer the question. |

With:
- 1 = bad
- 5 = excellent



**Definitions:**
- **Relevance:** Does it answer the question?
- **Accuracy:** Is it accurate in the context?
- **Clarity:** Is it understandable?

# Dowload Results

In [23]:
rows = []

for question, retrieval, answer in zip(
    questions,
    results_retriever,
    results_answer
):

    docs = retrieval["documents"][0]
    metas = retrieval["metadatas"][0]
    distances = retrieval["distances"][0]

    rows.append({
        "question": question["question"],

        "answer": answer,

        "doc_1": docs[0],
        "doc_2": docs[1],
        "doc_3": docs[2],

        "pmid_1": metas[0]["pmid"],
        "pmid_2": metas[1]["pmid"],
        "pmid_3": metas[2]["pmid"],

        "distance_1": distances[0],
        "distance_2": distances[1],
        "distance_3": distances[2],
    })

df_eval = pd.DataFrame(rows)
df_eval.head()

,question,answer,doc_1,doc_2,doc_3,pmid_1,pmid_2,pmid_3,distance_1,distance_2,distance_3
0,What is glioblastoma?,"{'results': {'ids': [['39513861_0', '40542948_...",The Three Pillars of Glioblastoma: A Systemati...,Unlocking glioblastoma: breakthroughs in molec...,Neurosurgical and neuro-oncological outcomes o...,39513861,40542948,41777607,0.480071,0.492108,0.506533
1,How is glioblastoma prognosis evaluated?,"{'results': {'ids': [['41091233_5', '39731064_...",Conditional 5-year survival after surviving on...,This systematic review summarizes the current ...,Molecular Biomarkers in Glioblastoma: A System...,41091233,39731064,36012105,0.359277,0.423970,0.428856
2,What MRI techniques are used for glioblastoma?,"{'results': {'ids': [['41749898_0', '42162948_...",Exploring the Role of Advanced MRI in Understa...,Impact on survival of glioblastoma patient's i...,"We aimed to show the safety of a small-margin,...",41749898,42162948,42134380,0.467751,0.532589,0.537395
3,What is peritumoral edema?,"{'results': {'ids': [['41740788_1', '42217213_...","(2) For 2 patients, we took the following meas...","Notwithstanding its benign classification, SM ...","All tumors showed significant enhancement, wit...",41740788,42217213,38254159,0.596067,0.755063,0.780171
4,What is pseudoprogression?,"{'results': {'ids': [['38992848_0', '40768078_...",Perioperative imaging predictors of tumor prog...,Artificial intelligence algorithms for differe...,Additional subclassification was performed bas...,38992848,40768078,40360047,1.095843,1.136668,1.234785

In [24]:
df_eval["retrieval"] = None
df_eval["retrieval_comments"] = ""

df_eval["relevance"] = None
df_eval["faithfulness"] = None
df_eval["clarity"] = None

In [25]:
df_eval["retrieval"] = [5,4,5,4,5,2,5,3,2,3]
df_eval["retrieval_comments"] = [
    "Two excellent definitional reviews in the top spots.",
    "Relevant documents on survival, biomarkers, and prognostic prediction. Not perfect, but sufficient.",
    "Excellent MRI documents, including a dedicated review.",
    "The literature clearly defines peritumoral edema even outside the context of glioblastoma.",
    "The best available evidence comes to light immediately (SR + meta-analysis).",
    "The documents focus primarily on tumor progression, not on its detection.",
    "Excellent summary, with a systematic review focused on biomarkers.",
    "A relevant review, but the other documents are not very relevant to the question.",
    "Documents that mention survival measures but do not provide a direct explanation from the OS.",
    "Treatments are available, but mainly in the context of recurrence or disease progression. They aren't really the standard treatments for GBM."
]

In [26]:
df_eval["relevance"] = [5,3,5,5,5,2,3,4,4,1]
df_eval["faithfulness"] = [5,4,5,5,5,4,5,3,5,5]
df_eval["clarity"] = [5,4,5,5,5,3,4,4,4,4]
df_eval["answer_comments"] = [
    "A short, accurate answer directly supported by the sources.",
    "Partially answers the question. The model focuses more on observed survival than on prognostic assessment.",
    "A direct and comprehensive answer.",
    "A clear and accurate definition.",
    "A very good definition of pseudoprogression.",
    "Off-topic response: factors influencing progression rather than detection methods.",
    "Correct, but too restrictive: only one biomarker is mentioned.",
    "A plausible answer, but several limitations seem to have been extrapolated from the context.",
    "Correctly answer the question using the OS's statistical measurement methods.",
    "The model implicitly acknowledges the lack of context. The response is accurate but does not answer the question."
]

In [27]:
df_eval.head()

,question,answer,doc_1,doc_2,doc_3,pmid_1,pmid_2,pmid_3,distance_1,distance_2,distance_3,retrieval,retrieval_comments,relevance,faithfulness,clarity,answer_comments
0,What is glioblastoma?,"{'results': {'ids': [['39513861_0', '40542948_...",The Three Pillars of Glioblastoma: A Systemati...,Unlocking glioblastoma: breakthroughs in molec...,Neurosurgical and neuro-oncological outcomes o...,39513861,40542948,41777607,0.480071,0.492108,0.506533,5,Two excellent definitional reviews in the top ...,5,5,5,"A short, accurate answer directly supported by..."
1,How is glioblastoma prognosis evaluated?,"{'results': {'ids': [['41091233_5', '39731064_...",Conditional 5-year survival after surviving on...,This systematic review summarizes the current ...,Molecular Biomarkers in Glioblastoma: A System...,41091233,39731064,36012105,0.359277,0.423970,0.428856,4,"Relevant documents on survival, biomarkers, an...",3,4,4,Partially answers the question. The model focu...
2,What MRI techniques are used for glioblastoma?,"{'results': {'ids': [['41749898_0', '42162948_...",Exploring the Role of Advanced MRI in Understa...,Impact on survival of glioblastoma patient's i...,"We aimed to show the safety of a small-margin,...",41749898,42162948,42134380,0.467751,0.532589,0.537395,5,"Excellent MRI documents, including a dedicated...",5,5,5,A direct and comprehensive answer.
3,What is peritumoral edema?,"{'results': {'ids': [['41740788_1', '42217213_...","(2) For 2 patients, we took the following meas...","Notwithstanding its benign classification, SM ...","All tumors showed significant enhancement, wit...",41740788,42217213,38254159,0.596067,0.755063,0.780171,4,The literature clearly defines peritumoral ede...,5,5,5,A clear and accurate definition.
4,What is pseudoprogression?,"{'results': {'ids': [['38992848_0', '40768078_...",Perioperative imaging predictors of tumor prog...,Artificial intelligence algorithms for differe...,Additional subclassification was performed bas...,38992848,40768078,40360047,1.095843,1.136668,1.234785,5,The best available evidence comes to light imm...,5,5,5,A very good definition of pseudoprogression.

In [28]:
version = 3
model = "qwen2.5:1.5b"
step = "corpus_improvement"

df_eval.to_csv(
    f"../data/evaluations/V{version}_{step}_evalN7_retriev_&_answ_model-{model}.csv",
    index=False
)

___

In [29]:
summary = {
    "retrieval_mean": df_eval["retrieval"].mean(),
    "relevance_mean": df_eval["relevance"].mean(),
    "faithfulness_mean": df_eval["faithfulness"].mean(),
    "clarity_mean": df_eval["clarity"].mean(),
}

In [30]:
print(summary)

{'retrieval_mean': np.float64(3.8), 'relevance_mean': np.float64(3.7), 'faithfulness_mean': np.float64(4.6), 'clarity_mean': np.float64(4.3)}

### V1

Means:

| Retrieval  | Relevance | Faithfulness | Clarity |
|:-----|:-----:|:-----:|:-----:|
| 2.3 | 3.2 | 4.3 | 3.7 |

### V2

Means:

| Retrieval  | Relevance | Faithfulness | Clarity |
|:-----|:-----:|:-----:|:-----:|
| 2.9 | 3.2 | 4.7 | 4.0 |

### Save

In [22]:
df_eval.to_csv(
    f"../data/evaluations/V{version}_{step}_evalN7_summary_model-{model}.csv",
    index=False
)